project:
  type: book
  preview: 
      port: 6969
  # pre-render: 
  #   - pip install -e ..

execute: 
  freeze: auto

crossref: 
  def-title: Takrif
  def-prefix: takrif
  thm-title: Hukum
  thm-prefix: hukum
  lem-title: Petua
  lem-prefix: petua
  eq-title: Persamaan
  eq-prefix: pers.
  appendix-title: Lampiran


book:
  title: "✨ Mekanik Kuantum 🐈"
  author: "Murthadza bin Aznam"
  date: now
  language: ms-MY
  search: true
  reader-mode: true
  repo-url: https://github.com/thaza-kun/mekanik-kuantum
  repo-actions: ['source']
  sharing: ['twitter', 'facebook']
  chapters:
    - part: index.qmd
      chapters:
        - pemuka/dorongan.qmd
        - pemuka/penulis.qmd
    - part: sinaran-jasad-hitam/index.qmd
      chapters:
        - sinaran-jasad-hitam/sejarah.qmd
        - sinaran-jasad-hitam/Planck.qmd
        - sinaran-jasad-hitam/taburan-Wien.qmd
        - sinaran-jasad-hitam/Rayleigh-Jeans.qmd
        - sinaran-jasad-hitam/sesaran-Wien.qmd
        - sinaran-jasad-hitam/Stefan-Boltzmann.qmd
        - sinaran-jasad-hitam/selingan.qmd
        - sinaran-jasad-hitam/pemalar-Planck.qmd
    - part: eksperimen/index.qmd
      chapters: 
        - eksperimen/kesan-fotoelektrik.qmd
        # - eksperimen/postulat-de-broglie.md
        # - eksperimen/Davisson-Germer.md
        # - eksperimen/Davisson-Thompson.md
        # - eksperimen/serakan-Compton.md
    # - part: gelombang
    #   chapters:
    #     - gelombang/nombor-kompleks.md
    #     - gelombang/bulatan-unit.md
    #     - gelombang/sifat-gelombang.md
    #     - gelombang/kalkulus.md
    #     - gelombang/fungsi-yang-diterima.md
    - part: schroedinger/index.qmd
      chapters:
        - schroedinger/andaian.qmd
        - schroedinger/fungsi-gelombang.qmd
        - schroedinger/operator.qmd
        - schroedinger/hamiltonan.qmd
        - schroedinger/nilai-jangkaan.qmd
        - schroedinger/arus-kebarangkalian.qmd
    # - part: penyelesaian
    #   chapters:
    #     - penyelesaian/zarah-bebas.md
    #     - penyelesaian/keupayaan-tangga.md
    #     - penyelesaian/sawar-keupayaan-tentu.md
    #     - penyelesaian/perigi-keupayaan-tentu.md
    #     - penyelesaian/perigi-keupayaan-infiniti.md
    #     - penyelesaian/keupayaan-kuadratik.md
    #     - penyelesaian/degenerat.md
    # - part: hidrogen
    #   chapters:
    #     - hidrogen/atom-Bohr.md
    #     - hidrogen/momentum-sudutan.md
    #     - hidrogen/fungsi-gelombang.md
  appendices:
    - sinaran-jasad-hitam/penyelesaian-berangka-sesaran-Wien.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    reference-location: section
    citation-location: document
  pdf:
    documentclass: scrreprt



